blank_issues_enabled: true
contact_links:
  - name: Secret Network Forum
    url: https://forum.scrt.network/
    about: Discuss and learn about issues on the Secret Network community forum. 
  - name: Secret Network Discord
    url: https://discord.com/invite/SJK32GY
    about: Join the Secret Network Discord server to discuss issues with the community. 
